### ISSUE TITLE
Expose functionality for passing custom directives

### ISSUE THREAD

**Issue by nripendra** [bloveit/graphql-utilities#9]
buildSchema does seem to support it while, build doesn't

```js
export default function buildSchema(schemaAST, { types, directives } = {}, typeDeps) {
...
}
```

**Comment by migueloller** [comment]
@nripendra,

Thanks for pointing this out! It's currently something that we want to add as I mentioned [here](https://github.com/bloveit/graphql-utilities/issues/5#issuecomment-245012757).

I've been pretty busy with other work lately so `graphql-utilities` hasn't gotten updated. I want to get `0.1.0` out soon, though.

If you want to submit a PR with this improvement yourself I would be more than glad to help you out with navigating the source code.

**Comment by nripendra** [comment]
@migueloller 

So, I'm planning to add an array for directives as:
```js
export default function build(source, config = {}, typeDeps = [], directives = [], infer = true) {
```
Now, I'd like to understand few points:

What are these assignments?

```js
/* eslint-disable no-param-reassign */
  if (Array.isArray(config) || typeof config === 'function') {
    infer = typeof typeDeps === 'boolean' ? typeDeps : true;
    typeDeps = config;
    config = {};
  }

  if (typeof config === 'boolean') {
    infer = config;
    typeDeps = [];
    config = {};
  }

  if (typeof typeDeps === 'boolean') {
    infer = typeDeps;
    typeDeps = [];
  }
  /* eslint-enable no-param-reassign */
```

How should this shuffling of parameters get affected when adding new parameter?

Finally in build Schema:
```js
export default function buildSchema(schemaAST, { types, directives } = {}, typeDeps) {
```
What's difference between types passed through { types, directives } and typeDeps?

**Comment by migueloller** [comment]
@nripendra,

Thanks for looking into this!

>So, I'm planning to add an array for directives as:
>```js
>export default function build(source, config = {}, typeDeps = [], directives = [], infer = true) {
>```
Because `build` is used for both types and a schema we really don't want to add another argument that only applies to just schemas. What we want to do is add the directives to the `config` argument. When building multiple types at the same time, the key used for the schema configuration should be `__schema` (open for suggestions here).

It would look something like this:
```js
const { __schema: Schema, Query } = build(`
  schema {
    query: Query
  }

  type Query {
    ok: Boolean!
  }
`, {
  __schema: {
    directives: [MyGraphQLDirective],
  },
  Query: {
    ok: () => true,
  },
});
```
>What are these assignments?
>```js
>/* eslint-disable no-param-reassign */
>  if (Array.isArray(config) || typeof config === 'function') {
>    infer = typeof typeDeps === 'boolean' ? typeDeps : true;
>    typeDeps = config;
>    config = {};
>  }
>
>  if (typeof config === 'boolean') {
>    infer = config;
>    typeDeps = [];
>    config = {};
>  }
>
>  if (typeof typeDeps === 'boolean') {
>    infer = typeDeps;
>    typeDeps = [];
>  }
>  /* eslint-enable no-param-reassign */
>```
>How should this shuffling of parameters get affected when adding new parameter?

This shuffling of parameters is mainly there to enable the developer to pass in type dependencies without having to pass the `config` argument. For `0.1.0` the arguments will be further simplified by removing inferred schema. The arguments then will just be the source, the config, and the type dependencies. What are your thoughts on this reshuffling? Is it useful or just confusing?

>Finally in build Schema:
>```js
>export default function buildSchema(schemaAST, { types, directives } = {}, typeDeps) {
>```
>What's difference between types passed through { types, directives } and typeDeps?

The different between the `types` passed into the config and `typeDeps` is that `typeDeps` are used by `build` to reference any type that might not be in the source template string. For example:
```js
build(`
  schema {
    query: Query
  }
`, [Query]) // Query has to be a type dependency because it is referenced in the template string.
```

You're probably wondering then why do we need the `types` field in the config. The reason is to be consistent with the `GraphQLSchema` constructor. It needs the `types` array for unions and interfaces. See [here](https://github.com/graphql/graphql-js/blob/master/src/type/schema.js#L96) for more info.

I hope this answers your questions. 😄 

Please let me know if you need anything else!
